### ISSUE TITLE
about test.csv 

### ISSUE THREAD

**Issue by Octalivia** [princeton-vl/surface_normals#3]
How can I use my own image data without a test.csv such as eigen_test_files_combine.csv? Or if I want to use my own image data, how can I generate this csv file?

**Comment by wfchen-umich** [comment]
Hi, the data in  eigen_test_files_combine.csv are relative depth pairs generated in the same way as  "Learning ordinal relationships for mid-level vision." CVPR 2015.
Please refer to that paper for details.
